-- Wave 2 Item 4: D1.25 Layout Director + D1.5 Genga Director + D2.5 Sakuga Kantoku

CREATE TABLE IF NOT EXISTS `panel_layouts` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `project_id` int NOT NULL,
  `episode_id` int NOT NULL,
  `scene_number` int NOT NULL,
  `panel_number` int NOT NULL,
  `camera_angle` varchar(50) NOT NULL,
  `camera_movement` varchar(50),
  `depth_layers` json,
  `character_placements` json,
  `composition_sketch_url` text,
  `composition_sketch_key` varchar(255),
  `layout_json` json,
  `generation_prompt` text,
  `generation_cost_usd` decimal(8,4) DEFAULT '0',
  `status` enum('pending','generating','generated','approved','rejected') NOT NULL DEFAULT 'pending',
  `approved_at` timestamp,
  `approved_by` int,
  `rejected_reason` text,
  `metadata` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_panel_layouts_episode` (`episode_id`, `scene_number`, `panel_number`),
  INDEX `idx_panel_layouts_project` (`project_id`),
  INDEX `idx_panel_layouts_status` (`status`)
);

CREATE TABLE IF NOT EXISTS `genga_keyframes` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `project_id` int NOT NULL,
  `episode_id` int NOT NULL,
  `scene_number` int NOT NULL,
  `panel_number` int NOT NULL,
  `layout_id` int,
  `sequence_index` int NOT NULL DEFAULT 0,
  `rough_genga_url` text,
  `rough_genga_key` varchar(255),
  `clean_genga_url` text,
  `clean_genga_key` varchar(255),
  `generation_prompt` text,
  `conditioning_inputs` json,
  `generation_cost_usd` decimal(8,4) DEFAULT '0',
  `attempt_number` int NOT NULL DEFAULT 1,
  `status` enum('pending','generating_rough','rough_ready','approved_rough','generating_clean','clean_ready','approved','rejected') NOT NULL DEFAULT 'pending',
  `approved_at` timestamp,
  `approved_by` int,
  `rejected_reason` text,
  `metadata` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_genga_episode` (`episode_id`, `scene_number`, `panel_number`),
  INDEX `idx_genga_layout` (`layout_id`),
  INDEX `idx_genga_status` (`status`)
);

CREATE TABLE IF NOT EXISTS `flip_book_previews` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `project_id` int NOT NULL,
  `episode_id` int NOT NULL,
  `scene_number` int NOT NULL,
  `frame_urls` json,
  `preview_video_url` text,
  `preview_video_key` varchar(255),
  `frame_count` int NOT NULL DEFAULT 0,
  `fps` int NOT NULL DEFAULT 8,
  `status` enum('pending','assembling','ready','approved','rejected') NOT NULL DEFAULT 'pending',
  `approved_at` timestamp,
  `approved_by` int,
  `rejected_reason` text,
  `generation_cost_usd` decimal(8,4) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_flipbook_episode` (`episode_id`, `scene_number`),
  INDEX `idx_flipbook_status` (`status`)
);

CREATE TABLE IF NOT EXISTS `sakuga_reviews` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `project_id` int NOT NULL,
  `episode_id` int NOT NULL,
  `review_type` enum('full_episode','scene','panel_range') NOT NULL DEFAULT 'full_episode',
  `scene_number` int,
  `panel_range` json,
  `punch_list` json,
  `issue_count` int NOT NULL DEFAULT 0,
  `critical_count` int NOT NULL DEFAULT 0,
  `warning_count` int NOT NULL DEFAULT 0,
  `info_count` int NOT NULL DEFAULT 0,
  `overall_score` decimal(5,2),
  `character_consistency_score` decimal(5,2),
  `perspective_score` decimal(5,2),
  `motion_arc_score` decimal(5,2),
  `color_consistency_score` decimal(5,2),
  `generation_cost_usd` decimal(8,4) DEFAULT '0',
  `status` enum('pending','reviewing','completed','acknowledged') NOT NULL DEFAULT 'pending',
  `acknowledged_at` timestamp,
  `acknowledged_by` int,
  `metadata` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sakuga_episode` (`episode_id`),
  INDEX `idx_sakuga_project` (`project_id`),
  INDEX `idx_sakuga_status` (`status`)
);
